# Generated by Django 4.2.30 on 2026-05-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('caller', models.CharField(max_length=100)),
                ('outcome', models.CharField(max_length=100)),
                ('sentiment', models.CharField(max_length=50)),
                ('review', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type_info', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LiveCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('intent', models.CharField(max_length=100)),
                ('tone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('change', models.CharField(max_length=50)),
                ('icon', models.CharField(default='IconPhone', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OutputRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting', models.TextField(default='Hi, this is Ava from Nexus. I can answer questions, qualify your request, or book a quick call with our team.')),
                ('qualification', models.TextField(default='Ask for company size, current call volume, timeline, budget range, and preferred meeting time.')),
                ('escalation', models.TextField(default='Transfer to a human for billing disputes, cancellation requests, legal questions, or high frustration.')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pass_rate', models.CharField(max_length=50)),
                ('focus', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SettingsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Nexus Voice Demo', max_length=200)),
                ('phone_number', models.CharField(default='+1 (415) 555-0198', max_length=50)),
                ('business_hours', models.CharField(default='weekday', max_length=100)),
                ('default_escalation', models.CharField(default='slack', max_length=50)),
                ('send_booked_summary', models.BooleanField(default=True)),
                ('alert_urgent_handoff', models.BooleanField(default=True)),
                ('email_daily_digest', models.BooleanField(default=True)),
                ('flag_negative_sentiment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('progress', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TriggerRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('status', models.CharField(default='Active', max_length=50)),
            ],
        ),
    ]
